import { randomBytes, createHash } from "node:crypto";
import bs58 from "bs58";
import {
  PublicKey,
  Transaction,
  SystemProgram,
  ComputeBudgetProgram,
} from "@solana/web3.js";
import { validBase58 } from "../core/input";
import { AppError } from "../shared/errors";
import { get, set } from "../backend/store";
import { rpc, verifyNetwork } from "./rpc";
export const DEMO_LAMPORTS = 1_000_000;
// Public destination only; a fresh recipient is generated by the fixture script before release.
export const demoReceiver = () => process.env.DEMO_RECEIVER_ADDRESS;
interface Prepared {
  wallet: string;
  messageHash: string;
  expiresAt: number;
  lastValidBlockHeight: string;
  receiver: string;
}
interface Receipt {
  signature: string;
  signedHash: string;
  state: "pending" | "success" | "failed";
  finality: string;
}
const hash = (bytes: Uint8Array) =>
  createHash("sha256").update(bytes).digest("hex");
export async function prepareDemo(wallet: string) {
  if (!validBase58(wallet, 32)) throw new AppError("INVALID_RECIPIENT");
  const receiver = demoReceiver();
  if (!receiver || !validBase58(receiver, 32))
    throw new AppError("DEMO_NOT_CONFIGURED", 503);
  if (wallet === receiver) throw new AppError("DEMO_SELF_TRANSFER");
  await verifyNetwork("devnet");
  const block = await rpc<{
    value: { blockhash: string; lastValidBlockHeight: bigint };
  }>("devnet", "getLatestBlockhash", [{ commitment: "confirmed" }]);
  const tx = new Transaction({
    feePayer: new PublicKey(wallet),
    recentBlockhash: block.value.blockhash,
  });
  tx.add(
    ComputeBudgetProgram.setComputeUnitLimit({ units: 20000 }),
    ComputeBudgetProgram.setComputeUnitPrice({ microLamports: 0 }),
    SystemProgram.transfer({
      fromPubkey: new PublicKey(wallet),
      toPubkey: new PublicKey(receiver),
      lamports: DEMO_LAMPORTS,
    }),
  );
  const transaction = tx
    .serialize({ requireAllSignatures: false, verifySignatures: false })
    .toString("base64");
  const simulation = await rpc<{ value: { err: unknown } }>(
    "devnet",
    "simulateTransaction",
    [
      transaction,
      { encoding: "base64", sigVerify: false, commitment: "confirmed" },
    ],
  );
  if (simulation.value.err) throw new AppError("DEMO_SIMULATION_FAILED", 422);
  const requestId = randomBytes(32).toString("hex"),
    expiresAt = Date.now() + 120000;
  await set(
    `prepare:${requestId}`,
    {
      wallet,
      receiver,
      messageHash: hash(tx.serializeMessage()),
      expiresAt,
      lastValidBlockHeight: block.value.lastValidBlockHeight.toString(),
    } satisfies Prepared,
    120,
  );
  return {
    requestId,
    transaction,
    network: "devnet",
    amount: "0.001",
    receiver,
    expiresAt,
  };
}
export function validateSigned(bytes: Uint8Array, prepared: Prepared) {
  let tx: Transaction;
  try {
    tx = Transaction.from(bytes);
  } catch {
    throw new AppError("INVALID_TRANSACTION");
  }
  if (
    hash(tx.serializeMessage()) !== prepared.messageHash ||
    tx.feePayer?.toBase58() !== prepared.wallet ||
    !tx.verifySignatures() ||
    !tx.signature
  )
    throw new AppError("TRANSACTION_CHANGED", 422);
  return { tx, signature: bs58.encode(tx.signature), signedHash: hash(bytes) };
}
export async function demoStatus(requestId: string) {
  const receipt = await get<Receipt>(`receipt:${requestId}`);
  if (!receipt) throw new AppError("DEMO_REQUEST_NOT_FOUND", 404);
  await verifyNetwork("devnet");
  const data = await rpc<{
    value: ({ err: unknown; confirmationStatus: string } | null)[];
  }>("devnet", "getSignatureStatuses", [
    [receipt.signature],
    { searchTransactionHistory: true },
  ]);
  const s = data.value[0];
  receipt.state = s?.err
    ? "failed"
    : s?.confirmationStatus === "finalized"
      ? "success"
      : "pending";
  receipt.finality = s?.confirmationStatus || "unknown";
  await set(`receipt:${requestId}`, receipt, 3600);
  return {
    signature: receipt.signature,
    state: receipt.state,
    finality: receipt.finality,
    network: "devnet",
  };
}
export async function submitDemo(requestId: string, transaction: string) {
  if (
    !/^[a-f0-9]{64}$/.test(requestId) ||
    transaction.length > 2200 ||
    !/^[A-Za-z0-9+/]+={0,2}$/.test(transaction)
  )
    throw new AppError("INVALID_TRANSACTION");
  const bytes = Buffer.from(transaction, "base64"),
    old = await get<Receipt>(`receipt:${requestId}`);
  if (old) {
    if (old.signedHash !== hash(bytes))
      throw new AppError("TRANSACTION_CHANGED", 422);
    return demoStatus(requestId);
  }
  const prepared = await get<Prepared>(`prepare:${requestId}`);
  if (!prepared || prepared.expiresAt <= Date.now())
    throw new AppError("DEMO_EXPIRED", 410);
  const signed = validateSigned(bytes, prepared);
  await verifyNetwork("devnet");
  const claimed = await set(
    `receipt:${requestId}`,
    {
      signature: signed.signature,
      signedHash: signed.signedHash,
      state: "pending",
      finality: "unknown",
    } satisfies Receipt,
    3600,
    true,
  );
  if (!claimed) return demoStatus(requestId);
  // Record signature before broadcast; an ambiguous response is pending, never a new payment.
  try {
    const signature = await rpc<string>("devnet", "sendTransaction", [
      transaction,
      {
        encoding: "base64",
        skipPreflight: false,
        preflightCommitment: "confirmed",
        maxRetries: 2,
      },
    ]);
    if (signature !== signed.signature)
      throw new AppError("RPC_INVALID_DATA", 502);
  } catch (error) {
    if (error instanceof AppError && error.code === "RPC_NETWORK_MISMATCH")
      throw error;
  }
  return demoStatus(requestId);
}
